### ISSUE TITLE
導入 gulp.js 

### ISSUE THREAD

**Issue by gonsakon** [kaohsiung-frontend/HospitalSupport#11]
導入 gulp.js
這篇寫得不錯：https://github.com/AnnaSu/gulp-example

功能需含有：
1.將所有js合併為1隻
2.檢測錯誤、壓縮、醜化js

只要做這樣就好，壓縮成一隻請要確定程式也可以run得起來

**Comment by hungjie19** [comment]
優先研究

**Comment by hungjie19** [comment]
gulp 導入包含：
合併 javascript = all.js
編譯 sass = all.css
處理 image
加上 webserver
監聽 js、sass、html 檔案變更既重新編譯對應程式

目前不知道如何實現: 
將 gulpfile 丟給專案夥伴後如何 gulp 建置環境

使用 bower ?

**Comment by gonsakon** [comment]
就把package.json跟gulpfile.js丟給他，
然後指定 npm install安裝plugin，就可以用gulp指令。

btw bower並不是拿來做這種事情的
