### ISSUE TITLE
新增一個tab頁面為：「醫院概況」，記錄每個病患狀況

### ISSUE THREAD

**Issue by gonsakon** [kaohsiung-frontend/HospitalSupport#5]
未出院: xx人  重傷: xx  中傷: xx  輕傷: xx
加護病房: xx人
一般病房: xx人

<img width="976" alt="2015-07-10 01 45 18" src="https://cloud.githubusercontent.com/assets/2187968/8602524/5d902f6c-26a5-11e5-9e19-d799ea84f891.png">

**Comment by bbandydd** [comment]
完成
