### ISSUE TITLE
在「醫院概況」用色塊長條圖，統計每間醫院的病患狀態

### ISSUE THREAD

**Issue by gonsakon** [kaohsiung-frontend/HospitalSupport#6]
如果長條圖做不出來，可先寫有xx人
<img width="977" alt="2015-07-10 01 46 36" src="https://cloud.githubusercontent.com/assets/2187968/8602558/88cc2906-26a5-11e5-8888-80090a688906.png">

**Comment by bbandydd** [comment]
完成
