### ISSUE TITLE
捐血車站

### ISSUE THREAD

**Issue by gonsakon** [kaohsiung-frontend/HospitalSupport#8]
這裏不合格！不能還多加個hr tag， .bloodInfo>h1 就可以做出來了，可以試試看用:before :after，那是個排版好工具，去搜尋一下資料吧
<img width="586" alt="2015-07-11 23 23 08" src="https://cloud.githubusercontent.com/assets/2187968/8634241/ebd70dca-2823-11e5-8b8c-38e8895776c4.png">

**Comment by hungjie19** [comment]
了解，原本是參考原始 color 結構的，排入修改:before :after

**Comment by hungjie19** [comment]
參考網站DEMO:  http://terkel.jp/demo/text-with-horizontal-line.html
