### ISSUE TITLE
git 開發流程以後請改成這樣

### ISSUE THREAD

**Issue by gonsakon** [kaohsiung-frontend/HospitalSupport#9]
gh-pages = 線上產品版本
develop = 開發用的分支

開發新功能、改bug都從develop開branch去改，
這個觀念部分可看這篇文章，看完再去看其他來補充觀念：
https://ihower.tw/blog/archives/5140

**Comment by hungjie19** [comment]
加入 develop 所有修增將合併至此測試，最後 merge 至 gh-pages 發布
